export const JOB_TITLES = [
  "Nhân viên nhập liệu dữ liệu",
  "Chuyên viên tuyển dụng",
  "Kế toán viên",
  "Biên tập viên nội dung",
  "Chuyên viên chăm sóc khách hàng",
  "Trợ lý pháp lý",
  "Chuyên viên phân tích dữ liệu",
  "Copywriter tiếp thị",
  "Chuyên viên dịch thuật",
  "Nhân viên telesale",
  "Chuyên viên SEO/SEM",
  "Trợ lý hành chính",
  "Chuyên viên báo cáo tài chính",
  "Nhân viên hỗ trợ kỹ thuật (Tier 1)",
  "Chuyên viên nghiên cứu thị trường",
  "Trợ lý tài chính",
  "Biên tập viên đồ hoạ",
  "Chuyên viên quản lý dự án",
  "Nhân viên kiểm soát chất lượng",
  "Chuyên viên phát triển kinh doanh",
  "Nhân viên hành chính tiền lương",
  "Chuyên viên marketing nội dung",
  "Trợ lý luật sư",
  "Nhân viên ghi chép cuộc họp",
  "Chuyên viên lên kế hoạch sự kiện",
  "Nhân viên xử lý đơn hàng",
  "Chuyên viên phân tích nguồn nhân lực",
  "Biên tập viên video",
  "Chuyên viên quản lý mạng xã hội",
  "Nhân viên dịch vụ khách hàng email",
  "Chuyên viên nghiên cứu người dùng",
  "Nhân viên lập lịch cuộc họp",
  "Chuyên viên chiến lược nội dung",
  "Trợ lý doanh nghiệp",
  "Nhân viên nhập dữ liệu bảo hiểm",
  "Chuyên viên quản lý hợp đồng",
  "Nhân viên kiểm tra hóa đơn",
  "Chuyên viên huấn luyện nội bộ",
  "Nhân viên phân loại tài liệu",
  "Chuyên viên cải thiện quy trình"
];
